### PR TITLE
added logout button

### PR DESCRIPTION
**Pull request by dknochen**

### CODE REVIEW

**Comment by dknochen** [comment]
@wcandillon please review and merge, thank you

**Comment by wcandillon** [comment]
The test doesn't seem to exist for this new button.
Also the test suite doesn't seem to work as is.

**Comment by wcandillon** [comment]
Could the logout be a dropdown of the username?
Also a test for it would be nice.

Currently the test suite does logout in a different manner. Would it be possible to unify? I see two log out functions right now. One in the controller, one the directive.

**Comment by dknochen** [comment]
@wcandillon could you please improve the ui? I can add a test later.

**Comment by wcandillon** [comment]
I added a test case for it and improved the css

**Pull request merged**
