### PR TITLE
Fix hypercube legalentity and improved filter behavior

### PR DESCRIPTION
**Pull request by dknochen**

### CODE REVIEW

**Comment by ghislainfourny** [comment]
LGTM. Approved ;-)

**Comment by wcandillon** [comment]
@dknochen Please add some tests.

**Comment by wcandillon** [comment]
@dknochen Does this affect the demo scenario at #85?

**Comment by dknochen** [comment]
@wcandillon yes, indeed. I will merge everything in the demo branch.

**Comment by wcandillon** [comment]
@MatthiasBrantner @dknochen Should we merge the demo branch into master instance of merging this into demo? In the spirit of short branch lifetime.

**Comment by dknochen** [comment]
@wcandillon for this branch there is no test, yet

**Comment by dknochen** [comment]
@wcandillon could you please review. Test for filters page is now included.

**Comment by dknochen** [comment]
@MatthiasBrantner could you review if time allows? William is not available, I guess.

**Comment by MatthiasBrantner** [comment]
@wcandillon is back. He’s a better candidate. ;-)

**Pull request merged**
