### PR TITLE
Recompile all formulas page

### PR DESCRIPTION
**Pull request by dknochen**

### CODE REVIEW

**Comment by dknochen** [comment]
@wcandillon ready for review

**Comment by MatthiasBrantner** [comment]
@dknochen Could you please help me understand what we need the recompile functionality for? Is this something we or our users need?

**Comment by wcandillon** [comment]
@dknochen @MatthiasBrantner do we need to add an issue to integrate the recompile-all mechanism and remove this secret url?

**Comment by dknochen** [comment]
@MatthiasBrantner if we discover a bug in the code generation of excel formulas then we need to recompile all formulas of a report at once. Right now, this is an admin and testing feature, but we need to integrate this in the complete picture. Not sure, how to do it correctly at the moment. IMHO this should be completely transparent to the user. For this we would need to be able to detect whether a report needs to be recompiled or not.

**Comment by dknochen** [comment]
@MatthiasBrantner @wcandillon https://github.com/28msec/nolap-report-editor/issues/122

**Pull request merged**
