### PR TITLE
Fix presentation Tree Bug

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by dknochen** [comment]
@wcandillon merges into master need to be reviewed (its as important as tests). We also need to restructure the unit test dir, I think (e.g. align it to the app dir structure https://github.com/28msec/nolap-report-editor/issues/89 ).

**Comment by wcandillon** [comment]
It was reviewed and approved by @MatthiasBrantner on email.

**Comment by dknochen** [comment]
@wcandillon Should we add a label for it? The reviewing workflow is not so nice right now ...

**Comment by wcandillon** [comment]
yes I agree!

**Pull request merged**
