### PR TITLE
Update color of the progress bar

### LINKED ISSUE #103: The progress bar is invisible
it's primary color over primary color.

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #103

### CODE REVIEW

**Comment by MatthiasBrantner** [comment]
Is this testable?

**Comment by wcandillon** [comment]
@MatthiasBrantner I couldn't come up with a test for that :-/

**Comment by MatthiasBrantner** [comment]
So you are breaking your own golden rule?

**Comment by wcandillon** [comment]
@MatthiasBrantner ready for review. Breaking the golden rule on this one.

**Pull request merged**
